version: "3.8"
services:
  server:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mariadb
  mariadb:
    platform: linux/x86_64
    image: "mariadb:latest"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: MP_Bank
      MYSQL_USER: root
      MYSQL_PASSWORD: senha
      MYSQL_ROOT_PASSWORD: senha